version: "3"

networks:
    parser:

services:
    redis:
        image: redis:latest
        container_name: technical_task_redis
        ports:
            - "6379:6379"
        networks:
            - parser
    nginx:
        container_name: technical_task_nginx
        image: nginx:1.20-alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - parser
    php:
        container_name: technical_task_php
        depends_on:
            - redis
        volumes:
            - .:/var/www/html
        build:
            dockerfile: Dockerfile
            context: .
        networks:
            - parser
